spring:
  datasource:
    url: ${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${POSTGRES_SCHEMAS}

    show-sql: true
  application:
    openApi:
      title: Redis API
      description: Redis API
      version: 1.0
      license:
        name: Apache License Version 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0
      name: Redis API
      url: http://localhost:8083
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION}
      refreshable-duration: ${JWT_REFRESHABLE_DURATION}
      valid-duration: ${JWT_VALID_DURATION}
  api:
    prefix: /api/v1



springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs